name: Test

on:
  pull_request:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: '3.38.7'
  DART_VERSION: '3.10.7'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Dart Version
        run: dart --version
      - name: Flutter Version
        run: flutter --version
      - name: env
        run: env
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
